package com.leetcode;

//e_389: Find the Difference
//Show Topic Tags

import org.junit.Assert;
import org.junit.Test;

/**
 *
 */

/*Description*/
//******************************************************************************************************************
//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.

//******************************************************************************************************************
//Companies: N/A
//******************************************************************************************************************
//Link: https://leetcode.com/problems/find-the-difference/
//******************************************************************************************************************

public class e_389_Find_the_Difference {


    public static void main(String[] args) {

        System.out.println(new e_389_Find_the_Difference().findTheDifference("abc", "abcde"));
    }

    public char findTheDifference(String s, String t) {
        //xor all elems will clear all similarities and will end up with the diff char
        char result = 0;
        //loop through first array and xor all elems
        for (char c : s.toCharArray()) {
            result ^= c;
        }

        //loop through second array and xor all elems
        for (char c : t.toCharArray()) {
            result ^= c;
        }

        return result;
    }



    @Test
    public void TestfindTheDifference() {
        Assert.assertEquals('d', findTheDifference("abc", "abcd"));
        Assert.assertEquals('e', findTheDifference("abcd", "aebcd"));
        Assert.assertEquals('e', findTheDifference("abrcd", "aebcrd"));
    }
}
